# Generated by Django 2.2.1 on 2019-06-06 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlineApp', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='db_folder',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineApp.College'),
        ),
    ]
